// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_DcDDFSIrK7NAhAI4Tp4TlUOpYXWUONI',
    appId: '1:1087018319920:web:a955615f66558a48f66df5',
    messagingSenderId: '1087018319920',
    projectId: 'parkassit-6e75b',
    authDomain: 'parkassit-6e75b.firebaseapp.com',
    databaseURL: 'https://parkassit-6e75b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'parkassit-6e75b.appspot.com',
    measurementId: 'G-4XGVTB8BL4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqeQ2dLpmHEyUUl1rSgrg47Llg3CTqQvs',
    appId: '1:1087018319920:android:b719285e29c3e3fcf66df5',
    messagingSenderId: '1087018319920',
    projectId: 'parkassit-6e75b',
    databaseURL: 'https://parkassit-6e75b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'parkassit-6e75b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3ayJdo7rPM_HlGhHMkU58B8DgmSr6ShA',
    appId: '1:1087018319920:ios:194f069ea103d470f66df5',
    messagingSenderId: '1087018319920',
    projectId: 'parkassit-6e75b',
    databaseURL: 'https://parkassit-6e75b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'parkassit-6e75b.appspot.com',
    iosBundleId: 'com.example.parkassisit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3ayJdo7rPM_HlGhHMkU58B8DgmSr6ShA',
    appId: '1:1087018319920:ios:194f069ea103d470f66df5',
    messagingSenderId: '1087018319920',
    projectId: 'parkassit-6e75b',
    databaseURL: 'https://parkassit-6e75b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'parkassit-6e75b.appspot.com',
    iosBundleId: 'com.example.parkassisit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_DcDDFSIrK7NAhAI4Tp4TlUOpYXWUONI',
    appId: '1:1087018319920:web:2b8269f9707e89d3f66df5',
    messagingSenderId: '1087018319920',
    projectId: 'parkassit-6e75b',
    authDomain: 'parkassit-6e75b.firebaseapp.com',
    databaseURL: 'https://parkassit-6e75b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'parkassit-6e75b.appspot.com',
    measurementId: 'G-XE93H7E99Q',
  );
}
